const ACTIVITY_ACTIONS = Object.freeze([
  'CREATE_TRIP',
  'UPDATE_TRIP',
  'DELETE_TRIP',
  'ADD_DESTINATION',
  'UPDATE_DESTINATION',
  'SELECT_ACCOMMODATION',
  'CREATE_BOOKING',
  'CANCEL_BOOKING',
  'STAFF_CONFIRM_BOOKING',
  'STAFF_CANCEL_BOOKING',
]);

const ACTIVITY_ACTION_SET = new Set(ACTIVITY_ACTIONS);
const ACTIVITY_ACTION_SQL = `ARRAY[${ACTIVITY_ACTIONS.map((action) => `'${action}'`).join(', ')}]::text[]`;

module.exports = { ACTIVITY_ACTIONS, ACTIVITY_ACTION_SET, ACTIVITY_ACTION_SQL };
